#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BetterGenshinImpact.GameTask.AutoHoeing.Models;
using BetterGenshinImpact.GameTask.AutoHoeing.Multiplayer;
using BetterGenshinImpact.GameTask.AutoHoeing.Multiplayer.Gateway;
using BetterGenshinImpact.GameTask.AutoHoeing.Multiplayer.Rerun;
using BetterGenshinImpact.GameTask.AutoPathing.Model;
using BetterGenshinImpact.Shared.CooperativeRerun;
using Xunit;
namespace BetterGenshinImpact.UnitTest.GameTaskTests.AutoHoeingTests;
public sealed class CooperativeRerunCommunicationTests
{
 private static CooperativeRoutePlan Plan(){var t=new PathingTask{FileName="route.json",FullPath="route.json",Positions=new()};var p=CooperativeRoutePlan.FromTask(new RouteInfo(),t,0,30);p.Manifest.RouteId="0:route";p.Manifest.Eligible=true;p.Manifest.Checkpoints.Add(new(){Id="s:0:fight:0",Segment=0,Kind="fight"});p.Manifest.Checkpoints.Add(new(){Id="s:0:tp",Segment=0,Kind="teleport"});p.FightPointIds[0]="s:0:fight:0";return p;}
 private static RerunSnapshot S(string sid,string scope,RerunStage stage,long rev,string route="",int index=0,IEnumerable<string>? resolved=null)=>new(){SessionId=sid,Scope=scope,Stage=stage,Revision=rev,CurrentRouteId=route,CurrentPlanIndex=index,PlanHash="hash",ResolvedPoints=resolved?.ToList()??new()};
 private static CoordinatorClient Client(Func<RerunRequest,int,RerunSnapshot> f,bool cap=true,List<RerunRequest>? seen=null){var c=new CoordinatorClient();c._testIsConnectedOverride=true;typeof(CoordinatorClient).GetField("_isInRoom",BindingFlags.Instance|BindingFlags.NonPublic)!.SetValue(c,true);var g=c.GetOrCreateGatewayForTest();typeof(BgiGatewayClient).GetProperty(nameof(BgiGatewayClient.ServerCapabilities),BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic)!.SetValue(g,cap?new[]{RerunProtocol.Capability}:Array.Empty<string>());g._testInvokeOverride=(m,e,ct)=>{var r=JsonSerializer.Deserialize<RerunRequest>(e.Payload!.ToJsonString(),GatewayJson.Options)!;seen?.Add(r);return Task.FromResult(new GatewayEnvelope{Type=GatewayProtocol.MessageTypes.Response,Name=e.Name,Payload=GatewayEnvelope.ToPayload(f(r,seen?.Count??1))});};return c;}
 [Fact] public async Task EnrollmentUsesServerSessionId(){var seen=new List<RerunRequest>();var c=Client((r,n)=>S("server",r.Scope,RerunStage.Normal,n),seen:seen);await using var s=await CooperativeRerunSession.StartAsync(c,Array.Empty<CooperativeRoutePlan>(),"round-1",CancellationToken.None);await s.SendAsync(RerunProtocol.Poll,ct:CancellationToken.None);Assert.Equal("",seen[0].SessionId);Assert.Equal("server",seen[1].SessionId);}
 [Fact] public async Task MissingCapabilityDoesNotEnroll(){var count=0;var c=Client((r,n)=>{count++;return S("s",r.Scope,RerunStage.Normal,n);},false);await Assert.ThrowsAsync<NotSupportedException>(()=>CooperativeRerunSession.StartAsync(c,Array.Empty<CooperativeRoutePlan>(),"round-1",CancellationToken.None));Assert.Equal(0,count);}
 [Fact] public async Task CompleteNormalSendsNoEmptyMarkAndPrepares(){var seen=new List<RerunRequest>();var c=Client((r,n)=>r.Operation==RerunProtocol.NormalDone?S("s",r.Scope,RerunStage.Preparing,n):r.Operation==RerunProtocol.Prepare?S("s",r.Scope,RerunStage.Running,n):S("s",r.Scope,RerunStage.Normal,n),seen:seen);await using var s=await CooperativeRerunSession.StartAsync(c,Array.Empty<CooperativeRoutePlan>(),"round-1",CancellationToken.None);Assert.Equal(RerunStage.Running,(await s.CompleteNormalAsync(CancellationToken.None)).Stage);Assert.DoesNotContain(seen,x=>x.Operation==RerunProtocol.Mark);Assert.Equal(new[]{RerunProtocol.Enroll,RerunProtocol.NormalDone,RerunProtocol.Prepare},seen.Where(x=>x.Operation!=RerunProtocol.Poll).Take(3).Select(x=>x.Operation));}
 [Fact] public async Task EmptyPlanCompletesWithoutPrepare(){var seen=new List<RerunRequest>();var c=Client((r,n)=>r.Operation==RerunProtocol.NormalDone?S("s",r.Scope,RerunStage.Completed,n):S("s",r.Scope,RerunStage.Normal,n),seen:seen);await using var s=await CooperativeRerunSession.StartAsync(c,Array.Empty<CooperativeRoutePlan>(),"round-1",CancellationToken.None);Assert.Equal(RerunStage.Completed,(await s.CompleteNormalAsync(CancellationToken.None)).Stage);Assert.DoesNotContain(seen,x=>x.Operation==RerunProtocol.Prepare);}
 [Fact] public async Task CompleteRouteWaitsForCurrentRouteToAdvance(){var p=Plan();var seen=new List<RerunRequest>();var polls=0;var c=Client((r,n)=>{if(r.Operation==RerunProtocol.Poll)polls++;return S("s",r.Scope,polls<2?RerunStage.Running:RerunStage.Finishing,n,polls<2?p.Manifest.RouteId:"",polls<2?0:1);},seen:seen);await using var s=await CooperativeRerunSession.StartAsync(c,new[]{p},"round-1",CancellationToken.None);await s.CompleteRouteAsync(s.CreateContext(p,true),RerunRouteOutcome.Completed,CancellationToken.None);Assert.True(polls>=2);}
 [Fact] public async Task FinishClosesFromFinishing(){var seen=new List<RerunRequest>();var c=Client((r,n)=>r.Operation==RerunProtocol.Finish?S("s",r.Scope,RerunStage.Completed,n):S("s",r.Scope,RerunStage.Finishing,n),seen:seen);await using var s=await CooperativeRerunSession.StartAsync(c,Array.Empty<CooperativeRoutePlan>(),"round-1",CancellationToken.None);await s.FinishAsync(CancellationToken.None);Assert.Contains(seen,x=>x.Operation==RerunProtocol.Finish);}
 [Fact] public async Task ContextRouteKeyAndArriveOnce(){var p=Plan();var seen=new List<RerunRequest>();var c=Client((r,n)=>S("s",r.Scope,RerunStage.Running,n,p.Manifest.RouteId,0,new[]{r.PointId}),seen:seen);await using var s=await CooperativeRerunSession.StartAsync(c,new[]{p},"round-1",CancellationToken.None);var x=s.CreateContext(p,true);Assert.Contains(p.Manifest.RouteId,x.BuildFightKey(0,0));await x.FastReportAsync("s:0:tp",CancellationToken.None);await x.WaitAsync("s:0:tp",CancellationToken.None);Assert.True(seen.Count(r=>r.Operation==RerunProtocol.Arrive&&r.PointId=="s:0:tp") >= 1);}
 [Fact] public async Task SnapshotIsolation(){var c=Client((r,n)=>S("s",r.Scope,RerunStage.Normal,n));await using var s=await CooperativeRerunSession.StartAsync(c,Array.Empty<CooperativeRoutePlan>(),"round-1",CancellationToken.None);var x=s.Snapshot;x.Participants.Add("mutated");Assert.DoesNotContain("mutated",s.Snapshot.Participants);}
}
