from pathlib import Path
import subprocess,json,hashlib,os,xml.etree.ElementTree as ET
r=Path.cwd();d=Path(__file__).parent;prev=d.parent/'auto-relay-history-outcome-20261004-from-01a10699';ns={'t':'http://microsoft.com/schemas/VisualStudio/TeamTest/2010'}
out=d/'legacy-final';out.mkdir(exist_ok=False);products=r/'_workflow/local-wait-admission-gates-20261004/g10-completion/products';base=prev/'final-r3'
paths=[x['path'] for x in json.loads((base/'candidate-observation.json').read_text(encoding='utf-8'))['sources']]
paths+=['Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/LegacyHistoricalSealIntegrityTests.cs','Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/HistoricalExecutionObservationTests.cs','MultiplayerHoeingAssistant/MultiplayerHoeingAssistant.csproj','Test/MultiplayerHoeingAssistant.UnitTest/MultiplayerHoeingAssistant.UnitTest.csproj']
paths+=['Test/R56ControlledWriterProbe/R56ControlledWriterProbe.csproj','Test/R56ControlledWriterProbe/Program.cs','MultiplayerHoeingAssistant/Directory.Build.targets']
def facts():return [dict(path=p,bytes=len(b:=(r/p).read_bytes()),lines=len(b.splitlines()),sha256=hashlib.sha256(b).hexdigest(),bom=b.startswith(b'\xef\xbb\xbf'),crlf=b.count(b'\r\n'),lf=b.count(b'\n')) for p in paths]
before=facts();(out/'source-before.json').write_text(json.dumps(before,indent=2),encoding='utf-8')
def run(name,args,env=None):
 with (out/(name+'.log')).open('wb') as f:code=subprocess.run(args,stdout=f,stderr=subprocess.STDOUT,env=env,timeout=600).returncode
 (out/(name+'-exit.txt')).write_text(str(code),encoding='utf-8');print(name,code,flush=True);return code
assert run('build',['dotnet','build','Test/MultiplayerHoeingAssistant.UnitTest/MultiplayerHoeingAssistant.UnitTest.csproj','-t:Rebuild','-p:DeployToBgiTools=false','-o',str(products),'--nologo'])==0
assert run('probe-build',['dotnet','build','Test/R56ControlledWriterProbe/R56ControlledWriterProbe.csproj','-t:Rebuild','-p:DeployToBgiTools=false','-o',str(products),'--nologo'])==0
assert (products/'ControlledWriterProbe.dll').is_file()
(out/'product-observation.json').write_text(json.dumps([dict(path=str(p.relative_to(r)),bytes=p.stat().st_size,sha256=sha256) for p in [products/'ControlledWriterProbe.dll',products/'MultiplayerHoeingAssistant.UnitTest.dll',products/'MultiplayerHoeingAssistant.dll'] for sha256 in [hashlib.sha256(p.read_bytes()).hexdigest()]],indent=2),encoding='utf-8')
def test(name,flt,env=None):return run(name,['dotnet','vstest',str(products/'MultiplayerHoeingAssistant.UnitTest.dll'),'/TestCaseFilter:'+flt,'/Logger:trx;LogFileName='+name+'.trx','/ResultsDirectory:'+str(out.resolve())],env)
assert test('history-matrix','FullyQualifiedName~OriginalHost_RunnerRecoveryUsesOriginalRoundAndStrictFacadeClosure|FullyQualifiedName~LegacyHistoricalSealIntegrityTests|FullyQualifiedName~HistoricalExecutionObservationTests|FullyQualifiedName~TerminalReleaseSealTests')==0
full=test('full','FullyQualifiedName~TaskCenter')
claims=r/'Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/ClaimSurfaceManifest.txt';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();cb=sha(claims);env=os.environ.copy();env['CLAIM_SURFACE_REGENERATE']='1';assert test('claims-regenerate','FullyQualifiedName~ClaimSurfaceGuardTests',env)==0
target=test('target','FullyQualifiedName~LegacyHistoricalSealIntegrityTests|FullyQualifiedName~HistoricalExecutionObservationTests|FullyQualifiedName~TerminalReleaseSealTests|FullyQualifiedName~TypedParent_|FullyQualifiedName~TypedAdmissionParentTests|FullyQualifiedName~ArbitrationAdmissionServiceTests|FullyQualifiedName~TaskCenterSuccessorPathGateTests|FullyQualifiedName~TaskCenterExternalStartAdmissionTests|FullyQualifiedName~TaskCenterHostRecoveryAdmissionTests|FullyQualifiedName~StartupHandoffHostTests|FullyQualifiedName~FacadeWaitLocallyConsumerTests|FullyQualifiedName~ClaimSurfaceGuardTests|FullyQualifiedName~StartupFlowSchemeStoreTests');assert target==0;assert facts()==before
def rows(p):return {x.get('testId'):dict(name=x.get('testName'),outcome=x.get('outcome'),message=x.findtext('t:Output/t:ErrorInfo/t:Message','',ns),stack=x.findtext('t:Output/t:ErrorInfo/t:StackTrace','',ns)) for x in ET.parse(p).findall('.//t:UnitTestResult',ns)}
a=rows(base/'full.trx')|rows(base/'target.trx');b=rows(out/'full.trx')|rows(out/'target.trx');comp=dict(kind='ordinary exact testId union, not certified',baseline_count=len(a),current_count=len(b),added=[dict(id=k,**b[k]) for k in sorted(b.keys()-a.keys())],removed=[dict(id=k,**a[k]) for k in sorted(a.keys()-b.keys())],changed=[dict(id=k,before=a[k],after=b[k]) for k in sorted(a.keys()&b.keys()) if a[k]['outcome']!=b[k]['outcome']],same_failed_ids={k for k in a if a[k]['outcome']=='Failed'}=={k for k in b if b[k]['outcome']=='Failed'},counts={c:sum(v['outcome']==c for v in b.values()) for c in ['Passed','Failed','NotExecuted']},failures=[dict(id=k,**v) for k,v in b.items() if v['outcome']=='Failed'])
(out/'impact-comparison.json').write_text(json.dumps(comp,ensure_ascii=False,indent=2),encoding='utf-8');obs=dict(kind='ordinary process/TRX/source byte observation; not certification/independent pass/IPC game User acceptance',sources=before,build_exit=0,full_exit=full,target_exit=target,full_counts={c:sum(v['outcome']==c for v in rows(out/'full.trx').values()) for c in ['Passed','Failed','NotExecuted']},target_counts={c:sum(v['outcome']==c for v in rows(out/'target.trx').values()) for c in ['Passed','Failed','NotExecuted']},claim_before=cb,claim_after=sha(claims),sources_unchanged=True,matrix_files=len(list((out/'matrix').glob('*.json'))),production_gate_open=False,goal_complete=False);(out/'candidate-observation.json').write_text(json.dumps(obs,ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps(obs['full_counts']),json.dumps(comp['counts']),comp['same_failed_ids'],obs['matrix_files'],flush=True)

