from pathlib import Path
import json,hashlib
r=Path.cwd();d=r/'_workflow/local-wait-admission-gates-20261004/typed-parent'
def edit(p,fn):
 f=r/p;b=f.read_bytes(); (d/(f.name+'.pre-harden.json')).write_text(json.dumps(dict(path=p,bytes=len(b),lines=len(b.splitlines()),sha256=hashlib.sha256(b).hexdigest(),bom=b.startswith(b'\xef\xbb\xbf'),crlf=b.count(b'\r\n'),lf=b.count(b'\n'))));s=b.decode('utf-8-sig').replace('\r\n','\n');new=fn(s);assert len(new)>.95*len(s);f.write_bytes((b'\xef\xbb\xbf' if b.startswith(b'\xef\xbb\xbf') else b'')+new.replace('\n','\r\n' if b'\r\n' in b else '\n').encode())
def store(s):
 s=s.replace('Persist(rec, expectedRecordRevision: 0);','Persist(rec, expectedRecordRevision: 0, authorizedParent: rec.AdmissionParentSource);')
 s=s.replace('RecoveryAssociationRecord? authorizedRecoveryAssociation = null, PreparedSendPermit? authorizedPermit = null)','RecoveryAssociationRecord? authorizedRecoveryAssociation = null, PreparedSendPermit? authorizedPermit = null, AdmissionParentSource? authorizedParent = null)')
 s=s.replace('        if (currentText is null && rec.RecoveryAssociations.Count != 0)','        if (currentText is null && rec.AdmissionParentSource is not null && rec.AdmissionParentSource != authorizedParent)\n            throw new RunRecordConflictException("新记录不能补造受理父来源。");\n        if (currentText is null && rec.RecoveryAssociations.Count != 0)')
 return s
edit('MultiplayerHoeingAssistant/Services/TaskCenter/RunStore.cs',store)
edit('MultiplayerHoeingAssistant/Services/TaskCenter/TaskCenterHost.cs',lambda s:s.replace('               && (run.Handoffs ?? []).Any(handoff => handoff is not null\n                   && handoff.Mode is StartupHandoffModes.Start or StartupHandoffModes.ArmTrigger);','               && run.AdmissionParentSource is { } original && original.MatchesHandoff(run);'))
edit('MultiplayerHoeingAssistant/Services/TaskCenter/TaskCenterHost.Admission.cs',lambda s:s.replace('                        && ArbitrationAdmissionService.IsFlowRegistrationParent(o, runId)\n                        && string.Equals(o.Candidate?.WorkflowId, workflowId, StringComparison.Ordinal))','                        && ArbitrationAdmissionService.IsFlowRegistrationParent(o, runId))').replace('return IsCanonicalAdmissionScope(scope0) && !string.IsNullOrEmpty(op.RequestIdentity)','return op.Candidate?.WorkflowId == workflowId && IsCanonicalAdmissionScope(scope0) && !string.IsNullOrEmpty(op.RequestIdentity)'))
edit('Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/StartupHandoffHostTests.cs',lambda s:s.replace('Assert.Equal("run-source:" + first.RunId, parent!.Value.RequestIdentity);','Assert.Equal("manual:exec-source", parent!.Value.RequestIdentity);\n            Assert.Equal(AdmissionParentKind.StartupHandoff, parent.Value.Kind);').replace('            var resolved = TaskCenterHost.ResolveAdmissionParent', '            var resolved = TaskCenterHost.ResolveAdmissionParent').replace('        var resolved = TaskCenterHost.ResolveAdmissionParent(sources, run, runId, wf);','        if (run is { AdmissionSourceScope: not null } && run.Handoffs.Count == 1)\n            run.AdmissionParentSource = AdmissionParentSource.Handoff(run, run.Handoffs[0]);\n        var resolved = TaskCenterHost.ResolveAdmissionParent(sources, run, runId, wf);').replace('Assert.Equal("run-source:" + runId, resolved!.Value.RequestIdentity);','Assert.Equal("fixture:matrix", resolved!.Value.RequestIdentity);\n            Assert.Equal(AdmissionParentKind.StartupHandoff, resolved.Value.Kind);'))
