from pathlib import Path
import subprocess,json,hashlib,os,xml.etree.ElementTree as ET
r=Path.cwd();d=r/'_workflow/local-wait-admission-gates-20261004/typed-parent/final';d.mkdir(exist_ok=False);products=r/'_workflow/local-wait-admission-gates-20261004/g10-completion/products'
paths=['MultiplayerHoeingAssistant/Models/TaskCenter/AdmissionParentSource.cs','MultiplayerHoeingAssistant/Models/TaskCenter/WorkflowRunModels.cs','MultiplayerHoeingAssistant/Models/TaskCenter/ArbitrationModels.cs','MultiplayerHoeingAssistant/Services/TaskCenter/RunStore.cs','MultiplayerHoeingAssistant/Services/TaskCenter/RunStoreEvidenceGuard.cs','MultiplayerHoeingAssistant/Services/TaskCenter/TaskCenterHost.cs','MultiplayerHoeingAssistant/Services/TaskCenter/TaskCenterHost.Admission.cs','MultiplayerHoeingAssistant/Services/TaskCenter/Arbitration/ArbitrationAdmissionService.cs','Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/TypedAdmissionParentTests.cs','Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/ArbitrationAdmissionServiceTests.cs','Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/TaskCenterSuccessorPathGateTests.cs','Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/StartupHandoffHostTests.cs','Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/FacadeWaitLocallyConsumerTests.cs']
def facts():
 return [dict(path=p,bytes=len(b:=(r/p).read_bytes()),lines=len(b.splitlines()),sha256=hashlib.sha256(b).hexdigest(),bom=b.startswith(b'\xef\xbb\xbf'),crlf=b.count(b'\r\n'),lf=b.count(b'\n')) for p in paths]
before=facts();(d/'source-before.json').write_text(json.dumps(before,indent=2))
def run(name,args,env=None):
 with (d/(name+'.log')).open('wb') as f:c=subprocess.run(args,stdout=f,stderr=subprocess.STDOUT,env=env).returncode
 (d/(name+'-exit.txt')).write_text(str(c));print(name,c,flush=True);return c
assert run('build',['dotnet','build','Test/MultiplayerHoeingAssistant.UnitTest/MultiplayerHoeingAssistant.UnitTest.csproj','-t:Rebuild','-p:DeployToBgiTools=false','-o',str(products),'--nologo'])==0
def test(name,filter,env=None):return run(name,['dotnet','vstest',str(products/'MultiplayerHoeingAssistant.UnitTest.dll'),'/TestCaseFilter:'+filter,'/Logger:trx;LogFileName='+name+'.trx','/ResultsDirectory:'+str(d)],env)
full=test('full','FullyQualifiedName~TaskCenter')
manifest=r/'Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/ClaimSurfaceManifest.txt';claimsBefore=hashlib.sha256(manifest.read_bytes()).hexdigest();env=os.environ.copy();env['CLAIM_SURFACE_REGENERATE']='1';assert test('claims-regenerate','FullyQualifiedName~ClaimSurfaceGuardTests',env)==0
target=test('target','FullyQualifiedName~TypedParent_|FullyQualifiedName~TypedAdmissionParentTests|FullyQualifiedName~ArbitrationAdmissionServiceTests|FullyQualifiedName~TaskCenterSuccessorPathGateTests|FullyQualifiedName~StartupHandoffHostTests|FullyQualifiedName~FacadeWaitLocallyConsumerTests|FullyQualifiedName~ClaimSurfaceGuardTests|FullyQualifiedName~StartupFlowSchemeStoreTests');assert target==0
assert facts()==before
ns={'t':'http://microsoft.com/schemas/VisualStudio/TeamTest/2010'}
def rows(p):return {x.get('testId'):dict(name=x.get('testName'),outcome=x.get('outcome'),message=x.findtext('t:Output/t:ErrorInfo/t:Message','',ns),stack=x.findtext('t:Output/t:ErrorInfo/t:StackTrace','',ns)) for x in ET.parse(p).findall('.//t:UnitTestResult',ns)}
old=r/'_workflow/local-wait-admission-gates-20261004/parent-capacity/final-r2';a=rows(old/'final-full.trx')|rows(old/'final-targeted.trx');b=rows(d/'full.trx')|rows(d/'target.trx')
comparison=dict(kind='ordinary exact testId/TRX union, not authenticated receipt',baseline_count=len(a),current_count=len(b),added=[dict(id=k,**b[k]) for k in sorted(b.keys()-a.keys())],removed=[dict(id=k,**a[k]) for k in sorted(a.keys()-b.keys())],changed=[dict(id=k,before=a[k],after=b[k]) for k in sorted(a.keys()&b.keys()) if a[k]['outcome']!=b[k]['outcome']],same_failed_ids={k for k in a if a[k]['outcome']=='Failed'}=={k for k in b if b[k]['outcome']=='Failed'},counts={c:sum(v['outcome']==c for v in b.values()) for c in ['Passed','Failed','NotExecuted']})
(d/'impact-comparison.json').write_text(json.dumps(comparison,ensure_ascii=False,indent=2))
obs=dict(kind='ordinary process/TRX/source bytes, not authenticated receipt/independent pass/product acceptance',sources=before,build_exit=0,full_exit=full,target_exit=target,full_counts={c:sum(v['outcome']==c for v in rows(d/'full.trx').values()) for c in ['Passed','Failed','NotExecuted']},target_counts={c:sum(v['outcome']==c for v in rows(d/'target.trx').values()) for c in ['Passed','Failed','NotExecuted']},claim_before=claimsBefore,claim_after=hashlib.sha256(manifest.read_bytes()).hexdigest(),sources_unchanged=True,comparison_summary={k:v for k,v in comparison.items() if k not in ['added','removed','changed']},production_gate_open=False,goal_complete=False)
(d/'candidate-observation.json').write_text(json.dumps(obs,ensure_ascii=False,indent=2));print(json.dumps(obs['full_counts']),json.dumps(comparison['counts']),comparison['same_failed_ids'],flush=True)
