from pathlib import Path
import json,hashlib,xml.etree.ElementTree as ET,subprocess
root=Path.cwd();base=root/'_workflow/local-wait-admission-gates-20261004';out=base/'original-send-round';ns={'t':'http://microsoft.com/schemas/VisualStudio/TeamTest/2010'}
load=lambda p:json.loads(p.read_text(encoding='utf-8-sig'))
def facts(p):
 return {r.get('testId'):{'test_id':r.get('testId'),'name':r.get('testName'),'outcome':r.get('outcome'),'message':r.findtext('t:Output/t:ErrorInfo/t:Message','',ns),'stack':r.findtext('t:Output/t:ErrorInfo/t:StackTrace','',ns)} for r in ET.parse(p).findall('.//t:UnitTestResult',ns)}
prior=facts(base/'cursor-consumption/final2-full.trx');prior.update(facts(base/'cursor-consumption/final2-startup-compat.trx'));current=facts(out/'final-full.trx');current.update(facts(out/'final-targeted-and-compat.trx'))
comparison={'kind':'exact testId union comparison, ordinary TRX observation','baseline_paths':['cursor-consumption/final2-full.trx','cursor-consumption/final2-startup-compat.trx'],'current_paths':['original-send-round/final-full.trx','original-send-round/final-targeted-and-compat.trx'],'baseline_count':len(prior),'current_count':len(current),'added':[current[i] for i in sorted(current.keys()-prior.keys())],'removed':[prior[i] for i in sorted(prior.keys()-current.keys())],'changed':[{'prior':prior[i],'current':current[i]} for i in sorted(prior.keys()&current.keys()) if prior[i]['outcome']!=current[i]['outcome']],'failed_id_set_equal':{i for i,r in prior.items() if r['outcome']=='Failed'}=={i for i,r in current.items() if r['outcome']=='Failed'},'counts':{o:sum(r['outcome']==o for r in current.values()) for o in ['Passed','Failed','NotExecuted']},'old_failures_not_exempted':True}
(out/'impact-comparison.json').write_text(json.dumps(comparison,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');sources=load(out/'candidate-source-set.json');mut=load(out/'mutations/observations.json');assert mut['all_subject_bytes_restored'] and len(mut['records'])==9 and mut['failure'] is None
for row in sources['facts']:assert hashlib.sha256((root/row['path']).read_bytes()).hexdigest()==row['sha256'],row['path']
for p,h in mut['final_sources'].items():assert hashlib.sha256((root/p).read_bytes()).hexdigest()==h,p
tests=[]
for p in sorted(out.glob('*.trx')):
 r=facts(p);tests.append({'path':str(p.relative_to(root)).replace('\\','/'),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'counts':{o:sum(x['outcome']==o for x in r.values()) for o in ['Passed','Failed','NotExecuted']},'failures':[x for x in r.values() if x['outcome']=='Failed']})
obs={'kind':'ordinary source/process/TRX/byte evidence; not authenticated current_regression receipt, independent implementation pass or product acceptance','thread_id':'01a10568-677c-7fc3-94b0-cc40c1f73165','head_observed_before_candidate_commit':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),'candidate_sources':sources['facts'],'tests':tests,'impact_comparison':'original-send-round/impact-comparison.json','final_build_exit':int((out/'final-build-exit.txt').read_text(encoding='utf-8-sig')),'final_full_exit':int((out/'final-full-test-exit.txt').read_text(encoding='utf-8-sig')),'final_targeted_and_compat_exit':int((out/'final-targeted-and-compat-exit.txt').read_text(encoding='utf-8-sig')),'current_unique_counts':comparison['counts'],'failed_test_ids':[i for i,r in current.items() if r['outcome']=='Failed'],'mutations':{'count':9,'source_bytes_restored':True,'evidence':'original-send-round/mutations/observations.json'},'final_product':{'path':'_workflow/local-wait-admission-gates-20261004/g10-completion/products/MultiplayerHoeingAssistant.UnitTest.dll','sha256':hashlib.sha256((base/'g10-completion/products/MultiplayerHoeingAssistant.UnitTest.dll').read_bytes()).hexdigest()},'all_original_obligations':'important/implementation/open retained','independent_requests_added':0,'g4_g7_closed':False,'production_gate_open':False,'goal_complete':False,'limitations':['Real IPC/game/User acceptance, full Stop/restart/data preservation, physical archived/history host recovery beyond controlled seams, all original obligations, full request accounting and independent comprehensive implementation review remain open.','Typed pre-job server rejection remains nonretryable; no relaxation. Canonical server SHA256 remains authoritative; missing legacy anchors remain Unknown.','Candidate configurations include actual BGI/client/build dependencies. Original frozen configuration and owner-policy=false remain; existing native prepare/gate cannot be falsely claimed passed.']}
(out/'candidate-observation.json').write_text(json.dumps(obs,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'current_counts':comparison['counts'],'added':len(comparison['added']),'removed':len(comparison['removed']),'changed':len(comparison['changed']),'failed_ids_equal':comparison['failed_id_set_equal'],'all_mutation_sources_restored':True},ensure_ascii=False))
