from pathlib import Path
r=Path.cwd();d=r/'_workflow/local-wait-admission-gates-20261004/auto-relay-original-multiround-20261004-from-01a10639';old=r/'_workflow/local-wait-admission-gates-20261004/auto-relay-four-entry-recovery-20261004-from-01a1061f/relay-prompt.txt'
s=old.read_text(encoding='utf-8-sig');first=s.splitlines()[0];assert first.startswith('/goal ')
current='''先建本批完整Goal（结果＋约束＋完成判据），再开工。最新标记AUTO-ORIGINAL-MULTIROUND-RELAY-20261004-FROM-01a10639，来源01a10639-2e7a-7392-9c6c-749342ecb428；唯一同项目local，cwd E:/Program Files/better-genshin-impact-LCB；本relay=_workflow/local-wait-admission-gates-20261004/auto-relay-original-multiround-20261004-from-01a10639。仍原共享包，不重开opening/历史/预算/请求/原级义务，不恢复旧Goal。
最新握手/唯一下一项以本段、本relay/HANDOFF.md及CURRENT-HANDOFF最新段为准，下方全部旧握手仅作历史，不执行。按handoff-inherit-model-20261004-v1继承实际gpt-6.1-sol/medium，证据本relay/source-model-observation.json；复杂独立综合审查sol/high不降强度。
先shell核cwd、get_goal查询本人，无Goal仅建一次完整摘要（限4000字符，绑定本relay-prompt全文/HANDOFF/CURRENT-HANDOFF及继承原完整范围），读回active；已有核完整范围不重建。只读核本人当前rollout最新turn_context.model/effort与collaboration_mode.settings一致且sol/medium，确认threadId；cwd/完整activeGoal/实际模型成立前禁改代码。保存get_goal完整返回本relay/new-goal-readback.json；保存actualCwd/threadId/marker/范围绑定/model/effort/settings/ordinal/rollout为new-handshake-observation.json，立即commentary握手结果。实际读本relay/old-goal-paused-readback.json，不凭文字认定来源paused；成立后自主继续，不等owner继续。
全文读本relay/HANDOFF.md、CURRENT-HANDOFF最新段，以及前relay（auto-relay-four-entry-recovery-20261004-from-01a1061f）/LIFECYCLE-CANDIDATE.md、final/candidate-observation.json、impact-comparison.json、全部原TRX/log、mutation-observations-r2.json、post-mutation-byte-observation.json、lifecycle-matrix-observation.json、candidate-commit-observation.json。产品候选27d5be3a1fd52471193fe6b0d7a9eb25af7dd3db，分支main-OldTeaBag-B168，HEAD动态核；保护材料外、不制造干净工作区。所有写入/突变恢复/Rebuild/测试终态，材料外R56/工具/csproj/文档不动。
本候选修复真实Paused恢复竞态：AdmitRecoveryAsync门面_gate维持至Sender接管/关闭完成，防Runner下一节点提前submission_conflict；文件事务锁不跨Sender await。10场景含两原父来源真实Paused续行、新Host Interrupted恢复、来源失效拒绝、32完整原发送记录TerminalPendingTransfer/256墓碑饱和拒绝及新Host保留。Interrupted崩溃状态模拟、产品扫描真实；不是子进程重启/IPC游戏User验收。最终Rebuild0，TaskCenter1981/18/2=2001、相邻425/0/2=427，精确合集2011相对2001新增10/删除0/共有变化0/18失败ID一致（不豁免），13输入字节一致、声明面同SHA、三个关键PFP指定断言/SHA恢复。初轮M2自有测试屏障悬挂终止并finally恢复、扫描前篡改移交被不可变守卫拒绝、编译/语义夹具过程全部保留且不当有效产品修复红。派生JSON cp936原字节在original-encoding保留，UTF8读回版附encoding-observation，原TRX/log/独立报告未编辑。保留原类型化d50c7e3/异步5c46c9a/容量e668f8d行为。
唯一下一共享转换：实际Host合法多sendSeq重试、所有前轮原nonce/确定未发送或拒绝依据、旧轮迟到受理冲突、关联发布后中断/严格结清失败/多history/outcome/封印、Stop/重开全部原责任。先完整状态/并发/故障/原轮次因果矩阵与红反例，再集中修复。已有OriginalHost_RunnerRecoveryUsesOriginalRoundAndStrictFacadeClosure在本相邻回归通过，不当全部G7链闭合；纯解析/Concat/Load/端口组装/能力true不是真实生产链证明。稳定完整共享链后核全部预算、认证真实来源、统一sol/high独立综合后审和原级成批闭环；全部原总功能实机及可运行版本仍为总Goal判据，不缩为局部夹具。
本来源新增独立请求0，旧可定位5次不是全G/control历史已核清。audit exit2仍原native请求缺receipt，manifest旧缺列表/policy=false/原planpass约束保留；修复既有材料配置或等价可核查独立只读来源，不翻policy/倒签/伪receipt/扩通用工具。正式认证/独立后审仍original-send-round/current-review-config.json和current-native-review-config.json完整源域，TRX不替认证。原请求/预算/等级保持，新增前核全账，8次/有限追加不重置。保护User/JS/.kiro/旧D盘，串行构建测试复用g10 products，自动明确范围本地候选提交，生产门关闭。必要语义交接继承当时实际模型档位；无hooks/心跳/后台merge，不按工具数/时间切换。
以下继承原完整范围和历史，旧最新/握手/唯一下一项仅由以上当前段覆盖，不执行历史握手，不重置原账：
'''
(d/'relay-prompt.txt').write_text(first+'\n\n'+current+'\n'+s.split('\n',1)[1],encoding='utf-8')
print('self-contained prompt saved',len((d/'relay-prompt.txt').read_bytes()))
