from pathlib import Path
import subprocess,json,hashlib
r=Path.cwd();d=Path(__file__).parent;owned=['MultiplayerHoeingAssistant/Services/TaskCenter/RunStoreTerminalRelease.cs','MultiplayerHoeingAssistant/Services/TaskCenter/TaskCenterHost.cs','Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/HistoricalExecutionObservationTests.cs','Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/TaskCenterSuccessorPathGateTests.cs'];origins=[]
for path,before in zip(owned,['RunStoreTerminalRelease.cs.before','TaskCenterHost.cs.before','historical-tests.before','successor-tests.before']):
 b=(d/before).read_bytes();head=subprocess.check_output(['git','show','HEAD:'+path]);match=b.replace(b'\r\n',b'\n')==head.replace(b'\r\n',b'\n');assert match,path;origins.append(dict(path=path,before_sha256=hashlib.sha256(b).hexdigest(),before_exact_matches_git_blob=b==head,before_matches_git_line_endings=match,current_sha256=hashlib.sha256((r/path).read_bytes()).hexdigest()))
final=json.loads((d/'final-r3/candidate-observation.json').read_text(encoding='utf-8'));assert all(hashlib.sha256((r/x['path']).read_bytes()).hexdigest()==x['sha256'] for x in final['sources'])
assert not subprocess.check_output(['git','diff','--cached','--name-only']).strip()
paths=owned+['_workflow/local-wait-admission-gates-20261004/CURRENT-HANDOFF.md']+[str(p.relative_to(r)).replace('\\','/') for p in sorted(d.rglob('*')) if p.is_file() and p.name not in ['candidate-commit-observation.json','git-status-after-commit.txt','commit-command.log','commit-paths.nul']];paths=sorted(set(paths))
before_head=subprocess.check_output(['git','rev-parse','HEAD']).decode().strip()
(d/'commit-before.json').write_text(json.dumps(dict(head=before_head,origins=origins,paths=paths,prior_attempts=['CRLF Git blob normalization check refused before mutation','Windows argv length refused git add before index mutation; HEAD/index verified unchanged'],kind='candidate checkpoint not certification/independent pass/acceptance'),indent=2),encoding='utf-8');paths.append(str((d/'commit-before.json').relative_to(r)).replace('\\','/'))
for i in range(0,len(paths),25):subprocess.run(['git','add','--',*paths[i:i+25]],check=True,capture_output=True)
pathfile=d/'commit-paths.nul';pathfile.write_bytes(b''.join(p.encode('utf-8')+b'\0' for p in paths))
with (d/'commit-command.log').open('wb') as f:code=subprocess.run(['git','commit','--only','-m','fix: reject ambiguous historical outcomes and recovery seals','--pathspec-from-file='+str(pathfile),'--pathspec-file-nul'],stdout=f,stderr=subprocess.STDOUT).returncode
assert code==0,(d/'commit-command.log').read_text(encoding='utf-8',errors='replace')
head=subprocess.check_output(['git','rev-parse','HEAD']).decode().strip();actual=subprocess.check_output(['git','diff-tree','--no-commit-id','--name-only','-r',head]).decode('utf-8').splitlines();assert set(owned).issubset(actual) and set(actual).issubset(paths)
assert all(hashlib.sha256((r/x['path']).read_bytes()).hexdigest()==x['sha256'] for x in final['sources']);post=subprocess.run(['git','status','--porcelain'],capture_output=True);(d/'git-status-after-commit.txt').write_bytes(post.stdout);(d/'git-status-after-commit.stderr.txt').write_bytes(post.stderr)
obs=dict(kind='local candidate checkpoint not independent pass/certification/product acceptance',before_head=before_head,commit=head,origins=origins,expected_paths=paths,actual_paths=actual,actual_changed_files=len(actual),product_source_files=2,test_source_files=2,full_counts=final['full_counts'],production_gate_open=False,goal_complete=False,source_bytes_unchanged=True,staged_after=subprocess.check_output(['git','diff','--cached','--name-only']).decode('utf-8'))
(d/'candidate-commit-observation.json').write_text(json.dumps(obs,ensure_ascii=False,indent=2),encoding='utf-8');print('candidate commit',head,'actual files',len(actual),'source bytes unchanged',flush=True)
