from pathlib import Path
import subprocess,json,hashlib
r=Path.cwd();d=Path(__file__).parent;relay=d.parent/'auto-relay-history-outcome-20261004-from-01a10699';o=json.loads((d/'final/candidate-observation.json').read_text(encoding='utf-8'))
assert all(hashlib.sha256((r/x['path']).read_bytes()).hexdigest()==x['sha256'] for x in o['sources'])
paths=['MultiplayerHoeingAssistant/Services/TaskCenter/Arbitration/ArbitrationAdmissionService.cs','MultiplayerHoeingAssistant/Services/TaskCenter/TaskCenterHost.Admission.cs','Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/ArbitrationAdmissionServiceTests.cs','Test/MultiplayerHoeingAssistant.UnitTest/ServiceTests/TaskCenter/TaskCenterExternalStartAdmissionTests.cs','_workflow/local-wait-admission-gates-20261004/CURRENT-HANDOFF.md']
paths+=sorted(str(p.relative_to(r)).replace('\\','/') for directory in [d,relay] for p in directory.rglob('*') if p.is_file() and p.suffix not in ['.pyc'] and p.name not in ['candidate-commit-observation.json','commit-before.json','commit-command.log','commit-paths.nul','current-status-before.txt','current-status-after.txt'])
paths=sorted(set(paths));before=dict(head=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),branch=subprocess.check_output(['git','branch','--show-current'],text=True).strip(),files=paths,source_bytes=o['sources'],kind='explicit candidate scope; not independent pass/acceptance')
(d/'commit-before.json').write_text(json.dumps(before,indent=2),encoding='utf-8');(d/'current-status-before.txt').write_bytes(subprocess.check_output(['git','status','--porcelain']))
for i in range(0,len(paths),25):subprocess.run(['git','add','--',*paths[i:i+25]],check=True,stdout=subprocess.DEVNULL)
pathfile=d/'commit-paths.nul';pathfile.write_bytes(b''.join(p.encode()+b'\0' for p in paths))
with (d/'commit-command.log').open('wb') as f:code=subprocess.run(['git','commit','--only','-m','fix: verify original external ledger causality during recovery','--pathspec-from-file='+str(pathfile),'--pathspec-file-nul'],stdout=f,stderr=subprocess.STDOUT).returncode
assert code==0,(d/'commit-command.log').read_text(errors='replace')
head=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip();files=subprocess.check_output(['git','diff-tree','--no-commit-id','--name-only','-r',head],text=True).splitlines();assert set(files)==set(paths),(len(files),len(paths));assert all(hashlib.sha256((r/x['path']).read_bytes()).hexdigest()==x['sha256'] for x in o['sources'])
(d/'candidate-commit-observation.json').write_text(json.dumps(dict(head=head,previous_head=before['head'],branch=before['branch'],actual_files=files,expected_files=paths,exit_code=code,source_bytes_unchanged=True,independent_pass=False,production_gate_open=False,goal_complete=False),indent=2),encoding='utf-8');(d/'current-status-after.txt').write_bytes(subprocess.check_output(['git','status','--porcelain']));print(json.dumps(dict(head=head,files=len(files),product_files=2,test_files=2,scope_verified=True)),flush=True)
